### ISSUE TITLE
SaaS deployment file specification

### ISSUE THREAD

**Issue by ARMmaster17** [ARMmaster17/Captain#191]
Thinking ahead for #173, there should probably be a specification for SaaS package deployments. Below is one proposal:
```yaml
- name: my-web-app
  blueprint:
    cpu: 1
    ram: 128
    disk: 4
  role: myservice/my-web-app/web
  support:
    - name: backend-db
      blueprint:
        cpu: 1
        ram: 1024
        disk: 20
      role: myservice/my-web-app/db
    - include: redis-service.yaml
```
